<template>
  <div>
    <div class="flex">
      <div
        class="w-full md:w-1/2 lg:w-1/2 xl:w-1/2 --forgot_password-interact-section min-h-screen bg-dark"
      >
        <div class="py-6 px-6 md:py-8 md:px-8 lg:py-10 lg:px-10">
          <div class="mb-12">
            <img src="/storage/sites/logo.png" class="h-10 w-auto">
          </div>
          <div v-if="success" class="mb-8 bg-green-300 font-bold text-white px-4 py-3 rounded relative" role="alert">
          <strong class="text-sm">Reset Akun Berhasil!</strong>
          <span class="block mt-1 text-xs">cek inbox di email kamu untuk reset akun kamu.</span>
        </div>
          <div class="mb-6 text-white mb-2">
            <span class="block text-lg font-semibold"> Lupa Password </span>
            <span class="text-sm">
              Bagi anda yang lupa password akun kamu
            </span>
          </div>
          <form @submit.prevent="forgot">
            <div class="mb-10">
              <label class="block text-gray-200 text-sm font-semibold mb-1"
                >E-mail</label
              >
              <input
                class="text-sm bg-dark-gray focus:bg-dark-gray appearance-none border-2 rounded w-full py-2 px-4 text-gray-200 leading-tight focus:outline-none focus:bg-white"
                :class="
                  form_errors.email
                    ? 'border-red-400 focus:border-red-400'
                    : 'border-dark-gray'
                "
                type="text"
                placeholder="alamat@email.com"
                v-model="form.email"
              />
              <div class="mt-1" v-if="form_errors.email">
                <span class="text-red-500 text-xs font-medium">
                  {{ form_errors.email[0] }}
                </span>
              </div>
            </div>
            <div class="mb-4 text-white flex items-center">
              <i
                data-feather="arrow-left"
                class="text-xs mr-1"
                style="max-width: 17px"
              ></i>
              <router-link
                :to="{ name: 'login' }"
                class="text-sm font-semibold"
                v-text="'Kembali Ke Masuk'"
              />
            </div>
            <button
              class="shadow-xl outline-none bg-primary w-full rounded-full text-dark font-bold py-2 px-4"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                style="
                  margin: auto;
                  background: none;
                  display: block;
                  shape-rendering: auto;
                "
                width="24px"
                height="24px"
                viewBox="0 0 100 100"
                preserveAspectRatio="xMidYMid"
                v-if="loading"
              >
                <circle
                  cx="50"
                  cy="50"
                  r="32"
                  stroke-width="8"
                  stroke="#000000"
                  stroke-dasharray="50.26548245743669 50.26548245743669"
                  fill="none"
                  stroke-linecap="round"
                >
                  <animateTransform
                    attributeName="transform"
                    type="rotate"
                    repeatCount="indefinite"
                    dur="1s"
                    keyTimes="0;1"
                    values="0 50 50;360 50 50"
                  ></animateTransform>
                </circle>
                <!-- [ldio] generated by https://loading.io/ -->
              </svg>
              <span v-else> Kirim </span>
            </button>
          </form>
        </div>
      </div>
      <div class="hidden md:block w-full relative">
        <div class="--forgot_password-image-section"></div>
      </div>
    </div>
  </div>
</template>

<script>
import api from "../api";

export default {
  data() {
    return {
      app_name: process.env.MIX_APP_NAME,
      loading: false,
      success: false,
      form: {
        email: "",
      },
      form_errors: {},
    };
  },

  mounted() {
    feather.replace();
    this.resizeForgotPasswordBackgroundImage();
    window.addEventListener("resize", (e) =>
      this.resizeForgotPasswordBackgroundImage()
    );
  },

  methods: {
    resizeForgotPasswordBackgroundImage() {
      const forgotPasswordImageSection = document.querySelector(
        ".--forgot_password-image-section"
      );

      if (forgotPasswordImageSection) {
        forgotPasswordImageSection.style.height = window.innerHeight + "px";

        forgotPasswordImageSection.style.width = forgotPasswordImageSection.parentElement.clientWidth + "px";
      }
    },

    async forgot() {
      if (!this.loading) {
        this.loading = true;
        this.form_errors = {};
        const response = await api
          .post("/forgot-password", this.form)
          .catch((e) => {
            this.loading = false;
            if (e.response.status === 422) {
              this.form_errors = e.response.data.errors;
            }
          });

        if (response) {
          this.loading = false;
          this.success = true;
          this.form = {
            email: ""
          }
          setTimeout(() => {
            this.success = false;
          }, 3000);
        }
      }
    },
  },
};
</script>
<style lang="scss" scoped>
.--forgot_password-interact-section {
  .container {
    padding: 2.5rem;
  }
}
.--forgot_password-image-section {
  position: relative;
  background: url("/storage/sites/bg-login.jpg");
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  background-color: #000;
  position: fixed;
  &::after {
    content:'\A';
    position:absolute;
    width:100%;
    height:100%;
    top:0; 
    left:0;
    background:rgba(0,0,0,0.3);
  }
}

input::placeholder {
  @apply text-gray-400;
}
</style>
